// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA24wgprFshCZXWrE5NLgGceJDQfYVydw',
    appId: '1:888390892983:web:65f19332adfb0659b33c32',
    messagingSenderId: '888390892983',
    projectId: 'paymentapp-6688d',
    authDomain: 'paymentapp-6688d.firebaseapp.com',
    storageBucket: 'paymentapp-6688d.appspot.com',
    measurementId: 'G-GYWBTSZ2FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI01xMpZyMLL-U1rxUdteq3treoLSIHfE',
    appId: '1:888390892983:android:cd28d440409a3790b33c32',
    messagingSenderId: '888390892983',
    projectId: 'paymentapp-6688d',
    storageBucket: 'paymentapp-6688d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgEkFt59xG9v_yEsSMFnAlfGWv5JeaCXc',
    appId: '1:888390892983:ios:81ccfcbd23ee4d7cb33c32',
    messagingSenderId: '888390892983',
    projectId: 'paymentapp-6688d',
    storageBucket: 'paymentapp-6688d.appspot.com',
    iosBundleId: 'com.example.paymentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgEkFt59xG9v_yEsSMFnAlfGWv5JeaCXc',
    appId: '1:888390892983:ios:81ccfcbd23ee4d7cb33c32',
    messagingSenderId: '888390892983',
    projectId: 'paymentapp-6688d',
    storageBucket: 'paymentapp-6688d.appspot.com',
    iosBundleId: 'com.example.paymentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA24wgprFshCZXWrE5NLgGceJDQfYVydw',
    appId: '1:888390892983:web:8470af49558a68e1b33c32',
    messagingSenderId: '888390892983',
    projectId: 'paymentapp-6688d',
    authDomain: 'paymentapp-6688d.firebaseapp.com',
    storageBucket: 'paymentapp-6688d.appspot.com',
    measurementId: 'G-BX9Y5ZYQXL',
  );

}